pipeline {
    agent any

    environment {
        DOCKERHUB_USER = 'dzikri2811'
        IMAGE_NAME = 'simple-app'
    }

    stages {
        stage('Checkout') {
            steps {
                echo '🔹 Mengambil source code dari GitHub...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                bat 'echo "🏗️  Build di Windows dimulai..."'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo '🐳 Membangun Docker image dari folder simple-app...'
                bat """
                    docker build -f simple-app/Dockerfile -t %DOCKERHUB_USER%/%IMAGE_NAME%:${BUILD_NUMBER} simple-app
                """
            }
        }

        stage('Push Docker Image') {
            steps {
                echo '🚀 Login ke Docker Hub dan push image...'
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    bat """
                        docker login -u %USER% -p %PASS%
                        docker push %DOCKERHUB_USER%/%IMAGE_NAME%:${BUILD_NUMBER}
                    """
                }
            }
        }
    }

    post {
        success {
            bat 'echo "✅ Pipeline selesai dijalankan."'
        }
        failure {
            bat 'echo "❌ Build gagal, periksa log untuk detail error."'
        }
    }
}
